### ISSUE TITLE
I would commit a Bug

### ISSUE THREAD

**Issue by ForrestAlfred** [MoZhouqi/KMNavigationBarTransition#4]
KMNavigationBarTransition is nice, but can be better.
When I push to a viewController in portrait, and then pop in landscape, the navigationBar image's frame do not change.
I guess that AutoLayout  should be applied to it.

**Comment by MoZhouqi** [comment]
Hi, the issue has been fixed in the latest release.

**Comment by ForrestAlfred** [comment]
Thanks, However I test with latest version 0.0.4, finding this bug is still existed.

**Comment by MoZhouqi** [comment]
Hi, I have tried the following steps in the example. 
1. Push a view controller in portrait
2. Rotate the screen to landscape
3. Pop the top view controller
![example](https://cloud.githubusercontent.com/assets/7426363/12573030/caf626fc-c42e-11e5-8a97-0556c0a0c3f6.gif)

It works fine. So could you please give me some more details to reproduce the problem?

**Comment by ForrestAlfred** [comment]
我新建了一个工程，测试在新工程里面这个issue 没问题了, 可能是与之前工程的缓存有关。
